# Configuration file for the Snakemake pipeline

# Path to the CSV file containing sample information
samples_file: "config/samples.csv"

# Path to conda environment
scanpy_env: '/private/home/jomojaco/miniforge3/envs/scanpy'
cyclum_env: '/private/home/jomojaco/miniforge3/envs/cyclum'

# Software paths
fastq_dir: "/private/groups/russelllab/jodie/sequencing_data/scRNAseq/PIP-seq_cells/Jacobs_10524_241203B9" # Add the path to the directory containing the FASTQ files for pipseq
combine_script: "../snakemake_scripts/analysis/integrate_h5ad_by_condition.py" 
kallisto_index: "../reference/KB_Drosophila_melanogaster_wMel_combined_16S/transcripts.idx" 
filter_script: "../snakemake_scripts/filtering/kallisto_bustools_qcfilter_adata.py"
cell_cycle_script: "../snakemake_scripts/analysis/cyclum_cell_cycle.py"
transcripts_to_genes: "../reference/KB_Drosophila_melanogaster_wMel_combined_16S/transcripts_to_genes.txt"

# Compute resources for cellranger 
cellranger_threads: 16
cellranger_cpus: 16
cellranger_mem: 500000  # MB
cellranger_time: "2:00:00"  # HH:MM:SS
cellranger_partition: "medium"  # SLURM partition for cellranger jobs

# Compute resources for pipseeker
pipseeker_threads: 16
pipseeker_cpus: 16
pipseeker_mem: 1000000  # MB
pipseeker_time: "2:00:00"  # HH:MM:SS
pipseeker_partition: "medium"  # SLURM partition for pipseeker jobs

# Compute resources for combining files
combine_threads: 128
combine_cpus: 4
combine_mem: 32000  # MB
combine_time: "2:00:00"  # HH:MM:SS
combine_partition: "medium"  # SLURM partition for combine jobs

# Compute resources for filter
filter_threads: 16
filter_cpus: 4
filter_mem: 1000000  # MB
filter_time: "48:00:00"  # HH:MM:SS
filter_partition: "long"  # SLURM partition for filter jobs

# Compute resources for cell cycle
cell_cycle_threads: 64           # Instead of 128
cell_cycle_mem: 128000           # Instead of 32000  
cell_cycle_time: "12:00:00"     # More time
cell_cycle_partition: "medium"  

# Extract 16S reads
target_gene: "GQX67_05945"
rRNA_regions: "../reference/rRNA/rRNA_regions.bed"
extract_gene_script: "../snakemake_scripts/filter_bus_by_gene.py"
ref_fasta: "../reference/rRNA/rRNA_reference_Dmel_wMel.fasta"
ref_bed: "../reference/rRNA/Dmel_wMel_rRNA.gene.bed"
plot_coverage_script: "../snakemake_scripts/rRNA_analysis/plot_coverage.py"
plot_blast_script: "../snakemake_scripts/rRNA_analysis/plot_blast_pie_charts.py"
min_blast_reads: 100
blast_db: "../blast_db/16S_ribosomal_RNA_plus_wolbachia"